[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
  set background=dark'''

[[plugins]]
repo = 'kana/vim-smartinput'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'racer-rust/vim-racer'

[[plugins]]
repo = 'rust-lang/rust.vim'
